import { Schema, model } from "mongoose";

const ChartOfAccountSchema = new Schema(
  {
    Code: { type: String, required: true }, // e.g., "O10201026"
    Name: { type: String, required: true }, // e.g., "Salaries of Elite Renewables"
    Balance: Number,
    CashAccount: String, // "tYES" / "tNO"
    BudgetAccount: String,
    ActiveAccount: String,
    PrimaryAccount: String,
    AccountLevel: Number,
    DataExportCode: String,
    FatherAccountKey: String,
    ExternalCode: String,
    RateConversion: String,
    TaxLiableAccount: String,
    TaxExemptAccount: String,
    ExternalReconNo: String,
    InternalReconNo: Number,
    AccountType: String, // e.g., "at_Expenses"
    AcctCurrency: String,
    Balance_syscurr: Number,
    Balance_FrgnCurr: Number,
    Protected: String,
    ReconciledAccount: String,
    LiableForAdvances: String,
    ForeignName: String,
    Details: String,
    ProjectCode: String,
    RevaluationCoordinated: String,
    LockManualTransaction: String,
    FormatCode: String,
    AllowChangeVatGroup: String,
    DefaultVatGroup: String,
    Category: String,
    TransactionCode: String,
    LoadingType: String,
    LoadingFactorCode: String,
    LoadingFactorCode2: String,
    LoadingFactorCode3: String,
    LoadingFactorCode4: String,
    LoadingFactorCode5: String,
    PlanningLevel: String,
    DatevAccount: String,
    DatevAutoAccount: String,
    DatevFirstDataEntry: String,
    AllowMultipleLinking: String,
    ProjectRelevant: String,
    DistributionRuleRelevant: String,
    DistributionRule2Relevant: String,
    DistributionRule3Relevant: String,
    DistributionRule4Relevant: String,
    DistributionRule5Relevant: String,
    BPLID: Number,
    BPLName: String,
    VATRegNum: String,
    AccountPurposeCode: String,
    ReferentialAccountCode: String,
    ValidFor: String,
    ValidFrom: Date,
    ValidTo: Date,
    ValidRemarks: String,
    FrozenFor: String,
    FrozenFrom: Date,
    FrozenTo: Date,
    FrozenRemarks: String,
    BlockManualPosting: String,
    CashFlowRelevant: String,
    PCN874ReportRelevant: String,
    PrimaryClosingAccount: String,
    CostAccountingOnly: String,
    CostElementRelevant: String,
    CostElementCode: String,
    StandardAccountCode: String,
    TaxonomyCode: String,
    IncomeClassificationCategory: String,
    IncomeClassificationType: String,
    ExpenseClassificationCategory: String,
    ExpenseClassificationType: String,
  },
  { timestamps: true }
);

export default model("ChartOfAccount", ChartOfAccountSchema);
