import { Schema, model } from "mongoose";

const OwnerSchema = new Schema(
  {
    EmployeeID: { type: Number, required: true },
    LastName: { type: String, required: true },
    FirstName: { type: String, required: true },
    MiddleName: String,
    Gender: String,
    JobTitle: String,
    EmployeeType: String,
    Department: Number,
    Branch: String,
    WorkStreet: String,
    WorkBlock: String,
    WorkZipCode: String,
    WorkCity: String,
    WorkCounty: String,
    WorkCountryCode: String,
    WorkStateCode: String,
    Manager: String,
    ApplicationUserID: String,
    SalesPersonCode: String,
    OfficePhone: String,
    OfficeExtension: String,
    MobilePhone: String,
    Pager: String,
    HomePhone: String,
    Fax: String,
    eMail: String,
    StartDate: Date,
    StatusCode: String,
    Salary: Number,
    SalaryUnit: String,
    EmployeeCosts: Number,
    EmployeeCostUnit: String,
    TerminationDate: Date,
    TreminationReason: String,
    BankCode: String,
    BankBranch: String,
    BankBranchNum: String,
    BankAccount: String,
    HomeStreet: String,
    HomeBlock: String,
    HomeZipCode: String,
    HomeCity: String,
    HomeCounty: String,
    HomeCountry: String,
    HomeState: String,
    DateOfBirth: Date,
    CountryOfBirth: String,
    MartialStatus: String,
    NumOfChildren: Number,
    IdNumber: String,
    CitizenshipCountryCode: String,
    PassportNumber: String,
    PassportExpirationDate: Date,
    Picture: String,
    Remarks: String,
    SalaryCurrency: String,
    EmployeeCostsCurrency: String,
    WorkBuildingFloorRoom: String,
    HomeBuildingFloorRoom: String,
    Position: String,
    AttachmentEntry: String,
    CostCenterCode: String,
    CompanyNumber: String,
    VacationPreviousYear: String,
    VacationCurrentYear: String,
    MunicipalityKey: String,
    TaxClass: String,
    IncomeTaxLiability: String,
    Religion: String,
    PartnerReligion: String,
    ExemptionAmount: Number,
    ExemptionUnit: String,
    ExemptionCurrency: String,
    AdditionalAmount: Number,
    AdditionalUnit: String,
    AdditionalCurrency: String,
    TaxOfficeName: String,
    TaxOfficeNumber: String,
    HealthInsuranceName: String,
    HealthInsuranceCode: String,
    HealthInsuranceType: String,
    SocialInsuranceNumber: String,
    ProfessionStatus: String,
    EducationStatus: String,
    PersonGroup: String,
    JobTitleCode: String,
    BankCodeForDATEV: String,
    DeviatingBankAccountOwner: String,
    SpouseFirstName: String,
    SpouseSurname: String,
    ExternalEmployeeNumber: String,
    BirthPlace: String,
    PaymentMethod: String,
    STDCode: String,
    CPF: String,
    CRCNumber: String,
    AccountantResponsible: String,
    LegalRepresentative: String,
    DIRFResponsible: String,
    CRCState: String,
    Active: String,
    IDType: String,
    BPLID: String,
    PassportIssueDate: Date,
    PassportIssuer: String,
    QualificationCode: String,
    PRWebAccess: String,
    PreviousPRWebAccess: String,
    WorkStreetNumber: String,
    HomeStreetNumber: String,
    LinkedVendor: String,
    CreateDate: Date,
    CreateTime: String,
    UpdateDate: Date,
    UpdateTime: String,
    EmployeeCode: String,
    ARetSEFAZ: String,
    U_EmplId: String,

    // Arrays from SAP data
    EmployeeAbsenceInfoLines: [Schema.Types.Mixed],
    EmployeeEducationInfoLines: [Schema.Types.Mixed],
    EmployeeReviewsInfoLines: [Schema.Types.Mixed],
    EmployeePreviousEmpoymentInfoLines: [Schema.Types.Mixed],
    EmployeeRolesInfoLines: [Schema.Types.Mixed],
    EmployeeSavingsPaymentInfoLines: [Schema.Types.Mixed],
    EmployeeBranchAssignment: [Schema.Types.Mixed],
  },
  { timestamps: true }
);

export default model("Owner", OwnerSchema);
