import { Schema, model } from "mongoose";

const WarehouseSchema = new Schema(
  {
    Street: String,
    StockInflationOffsetAccount: String,
    ZipCode: String,
    DecreasingAccount: String,
    PurchaseAccount: String,
    EURevenuesAccount: String,
    ReturningAccount: String,
    ShippedGoodsAccount: String,
    StockInflationAdjustAccount: String,
    AllowUseTax: String,
    CostInflationAccount: String,
    ForeignExpensesAccount: String,
    EUExpensesAccount: String,
    CostInflationOffsetAccount: String,
    ExpensesClearingAccount: String,
    PurchaseReturningAccount: String,
    VATInRevenueAccount: String,
    FederalTaxID: String,
    Location: Number,
    Block: String,
    ExpenseAccount: String,
    DecreaseGLAccount: String,
    RevenuesAccount: String,
    TaxGroup: String,
    ExemptRevenuesAccount: String,
    PurchaseOffsetAccount: String,
    CostOfGoodsSold: String,
    WarehouseCode: { type: String, required: true },
    State: String,
    City: String,
    PriceDifferencesAccount: String,
    VarianceAccount: String,
    Country: String,
    IncreaseGLAccount: String,
    ExchangeRateDifferencesAccount: String,
    WIPMaterialAccount: String,
    WarehouseName: { type: String, required: true },
    DropShip: String,
    WIPMaterialVarianceAccount: String,
    TransfersAcc: String,
    InternalKey: Number,
    ForeignRevenuesAcc: String,
    BuildingFloorRoom: String,
    County: String,
    Nettable: String,
    IncreasingAcc: String,
    ExpenseOffsetingAct: String,
    GoodsClearingAcc: String,
    StockAccount: String,
    BusinessPlaceID: Number,
    PurchaseCreditAcc: String,
    EUPurchaseCreditAcc: String,
    ForeignPurchaseCreditAcc: String,
    SalesCreditAcc: String,
    SalesCreditEUAcc: String,
    ExemptedCredits: String,
    SalesCreditForeignAcc: String,
    NegativeInventoryAdjustmentAccount: String,
    WHShipToName: String,
    Excisable: String,
    WHIncomingCenvatAccount: String,
    WHOutgoingCenvatAccount: String,
    StockInTransitAccount: String,
    WipOffsetProfitAndLossAccount: String,
    InventoryOffsetProfitAndLossAccount: String,
    AddressType: String,
    StreetNo: String,
    Storekeeper: String,
    Shipper: String,
    ManageSerialAndBatchNumbers: String,
    GlobalLocationNumber: String,
    EnableBinLocations: String,
    BinLocCodeSeparator: String,
    DefaultBin: String,
    DefaultBinEnforced: String,
    AutoAllocOnIssue: String,
    EnableReceivingBinLocations: String,
    ReceivingBinLocationsBy: String,
    PurchaseBalanceAccount: String,
    Inactive: String,
    RestrictReceiptToEmptyBinLocation: String,
    ReceiveUpToMaxQuantity: String,
    AutoAllocOnReceipt: String,
    ReceiveUpToMaxWeight: String,
    ReceiveUpToMethod: String,
    LegalText: String,
    U_Type: String,
    U_PrjCode: String,
  },
  { timestamps: true }
);

export default model("Warehouse", WarehouseSchema);
